# Generated by Django 3.2.6 on 2021-08-04 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('createdat', models.CharField(blank=True, db_column='createdAt', max_length=255, null=True)),
                ('content', models.TextField(blank=True, null=True)),
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('main_id', models.IntegerField()),
                ('depth', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'comments',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                
                ('id', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('createdat', models.CharField(blank=True, db_column='createdAt', max_length=255, null=True)),
                ('content', models.TextField(blank=True, null=True)),
                ('main_id', models.IntegerField()),
                ('hotscore', models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True)),
                ('image', models.CharField(blank=True, max_length=400, null=True)),
            ],
            options={
                'db_table': 'posts',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('password', models.CharField(blank=True, max_length=60, null=True)),
             
            ],
            options={
                'db_table': 'users',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Votes',
            fields=[
                ('id', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('score', models.IntegerField(blank=True, null=True)),
                ('uid', models.CharField(blank=True, max_length=255, null=True, unique=True)),
            ],
            options={
                'db_table': 'votes',
                'managed': False,
            },
        ),
    ]
