# Generated by Django 3.2.6 on 2021-08-09 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_auto_20210808_1753'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(blank=True, default='sdfsdf', max_length=255),
            preserve_default=False,
        ),
    ]
