# Generated by Django 3.2.6 on 2021-08-09 04:16

from django.db import migrations, models
import posts.models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_alter_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.CharField(default=posts.models.assignId, max_length=255, primary_key=True, serialize=False),
        ),
       
    ]
